### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by strugee** [PuercoPop/nyan-prompt#3]
This will allow the project to be published on MELPA Stable.

**Comment by PuercoPop** [comment]
Oi, thank for your interest. I've pushed a tag following semver. Is that all there is to do? I couldn't find a guideline about melpa stable requirements.

**Comment by strugee** [comment]
AFAIK, that's it. IIIUC, since you're already in MELPA, you should be picked up for MELPA Stable too.

**Comment by strugee** [comment]
Yep!

http://stable.melpa.org/#/nyan-prompt
