### ISSUE TITLE
Please provide gif image

### ISSUE THREAD

**Issue by azzamsa** [PuercoPop/nyan-prompt#6]
Please provide gif image in readme section.

**Comment by PuercoPop** [comment]
There is no animation, so a GIF is not needed. This is how it looks like

![image](https://user-images.githubusercontent.com/387111/44295586-6daf2880-a271-11e8-840e-3d6c757e2451.png)

**Comment by azzamsa** [comment]
Oh I think it's moving like nyan-mode.

Don't you consider to put that in README ?
